[package]
name = "bfs_rapier"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_rapier2d = { version = "0.27.0", features = [
  "debug-render-2d",
  "parallel",
  "simd-stable",
] }
bfs_core = { path = "../bfs_core" }
bfs_movement = { path = "../bfs_movement" }
