[package]
name = "bevy_falling_sand"
version = "0.3.0"
edition = "2021"
authors = ["Jeff Barfield <jeffreybarfield@protonmail.com>"]
license-file = "./LICENSE"
repository = "https://github.com/noprobelm/bevy_falling_sand"
readme = "README.md"
description = "Falling Sand simulation plugin for Bevy"
keywords = ["falling-sand", "simulation", "physics"]
exclude = ["examples", "docs", ".github", ".gitignore", "assets", "CHANGELOG.org"]
documentation = "http://docs.rs/bevy_falling_sand"
categories = ["game-engines", "game-development"]

[dependencies]
bfs_internal = { path = "crates/bfs_internal" }
bevy = { version = "0.15", features = ["wayland"] }

[dev-dependencies]
bevy-inspector-egui = "0.28"
bevy_egui = "0.31"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
