[package]
name = "bevy_falling_sand"
version = "0.2.0"
edition = "2021"
authors = ["Jeff Barfield <jeffreybarfield@protonmail.com>"]
license-file = "./LICENSE"
repository = "https://github.com/noprobelm/bevy_falling_sand"
readme = "README.md"
description = "Falling Sand simulation plugin for Bevy"
keywords = ["falling-sand", "simulation", "physics"]
exclude = ["examples", "docs", ".github", ".gitignore", "assets"]
documentation = "http://docs.rs/bevy_falling_sand"
categories = ["game-engines", "game-development"]

[dependencies]
ahash = "0.8.11"
bevy = "0.14.0"
bevy_turborand = "0.9.0"
rayon = "1.10.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
