[package]
name = "bevy_falling_sand"
version = "0.5.0"
edition = "2021"
authors = ["Jeff Barfield <jeffreybarfield@protonmail.com>"]
license-file = "./LICENSE"
repository = "https://github.com/noprobelm/bevy_falling_sand"
readme = "README.md"
description = "Falling Sand simulation plugin for Bevy"
keywords = ["falling-sand", "simulation", "physics"]
exclude = [
  "examples",
  "docs",
  ".github",
  ".gitignore",
  "assets",
  "CHANGELOG.org",
]
documentation = "http://docs.rs/bevy_falling_sand"
categories = ["game-engines", "game-development"]

[workspace]
members = [
  "crates/bfs_internal",
  "crates/bfs_core",
  "crates/bfs_movement",
  "crates/bfs_debug",
  "crates/bfs_color",
  "crates/bfs_spatial",
  "crates/bfs_reactions",
  "crates/bfs_physics",
  "crates/bfs_reactions",
  "crates/bfs_scenes",
]

[workspace.dependencies]
bevy = { version = "0.16", features = ["wayland"] }

[dependencies]
bfs_internal = { path = "crates/bfs_internal" }
bevy.workspace = true

[dev-dependencies]
bevy_egui = "0.34.1"
bevy_turborand = "0.11.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = true

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
