[package]
name = "bevy_falling_sand"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_turborand = "0.8.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
