[package]
name = "bfs_reactions"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_turborand = "0.11.0"
bfs_color = { path = "../bfs_color" }
bfs_core = { path = "../bfs_core" }
