[package]
name = "bfs_movement"
version = "0.5.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bfs_core = { version = "0.5.0", path = "../bfs_core" }
bevy_turborand = "0.11.0"
serde = "1.0.210"
smallvec = { version = "1.13.2", features = ["serde"] }
