[package]
name = "bfs_movement"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bfs_core = { path = "../bfs_core" }
bevy_turborand = "0.11.0"
serde = "1.0.210"
smallvec = "1.13.2"
