[package]
name = "bfs_color"
version = "0.5.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_turborand = "0.11.0"
serde = "1.0.210"
bfs_core = { version = "0.5.0", path = "../bfs_core" }
