[package]
name = "bfs_debug"
version = "0.5.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bfs_core = { path = "../bfs_core" }
bfs_movement = { path = "../bfs_movement" }
bfs_physics = { path = "../bfs_physics" }
