[package]
name = "bfs_physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
avian2d = { version = "0.3.1", features = ["debug-plugin"] }
bfs_core = { path = "../bfs_core" }
bfs_movement = { path = "../bfs_movement" }
earcutr = "0.5.0"
